// Generated by CoffeeScript 1.4.0
(function() {
  var PouchCore;

  PouchCore = (function() {

    function PouchCore(remoteUrl, onChange) {
      var parts,
        _this = this;
      this.remoteUrl = remoteUrl;
      this.onChange = onChange;
      if (this.remoteUrl.slice(0, 4) === "http") {
        parts = this.remoteUrl.split("/");
        this._dbName = parts.pop();
        while (this._dbName === "") {
          this._dbName = parts.pop();
        }
      }
      Pouch(this._dbName, function(e, db) {
        var _from, _to;
        if (!e) {
          _this.db = db;
          _this.db.changes({
            continuous: true,
            include_docs: true,
            onChange: _this.onChange
          });
          _to = _this.db.replicate.to(_this.remoteUrl, {
            continuous: true
          });
          _from = _this.db.replicate.from(_this.remoteUrl, {
            continuous: true
          });
          _this.up = true;
          _this.stop = function() {
            console.log("stopped");
            _this.up = false;
            _to.cancel();
            _from.cancel();
            return _this;
          };
          _this.start = function() {
            if (!_this.up) {
              _this.up = true;
              _to = _this.db.replicate.to(_this.remoteUrl, {
                continuous: true
              });
              _from = _this.db.replicate.from(_this.remoteUrl, {
                continuous: true
              });
            }
            return _this;
          };
          return _this;
        } else {
          return Pouch(_this.remoteUrl, function(e, db) {
            if (!e) {
              _this.db;
              _this.db.changes({
                continuous: true,
                include_docs: true,
                onChange: _this.onChange
              });
              return _this;
            } else {
              return "yeah something went wrong";
            }
          });
        }
      });
    }

    PouchCore.prototype.add = function(doc, cb) {
      if (cb == null) {
        cb = function() {
          return true;
        };
      }
      if (!("_id" in doc)) {
        return this.db.post(doc, cb);
      } else if ("_id" in doc && doc._id.slice(0, 8) !== "_design/") {
        return this.db.put(doc, cb);
      } else if (doc.length) {
        return this.db.bulkDocs(doc, cb);
      }
    };

    PouchCore.prototype.get = function(id, cb) {
      if (cb == null) {
        cb = function() {
          return true;
        };
      }
      return this.db.get(id, cb);
    };

    PouchCore.prototype.remove = function(id, cb) {
      var _this = this;
      if (cb == null) {
        cb = function() {
          return true;
        };
      }
      return this.get(id, function(err, doc) {
        if (!err) {
          _this.db.remove(doc, cb);
        }
        if (err) {
          return cb("err");
        }
      });
    };

    return PouchCore;

  })();

}).call(this);
